version: '3'
services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile.server
    container_name: sales-service-server
    ports:
      - "50054:50054"
    env_file:
      - .env
    volumes:
      - ./server:/app
  client:
    build: 
      context: .
      dockerfile: Dockerfile.client
    container_name: sales-service-client
    ports:
      - "8083:8083"
    env_file:
      - .env
    volumes:
      - ./client:/app
